[package]
name = "eaip2sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eaip = "0.1.0"
tokio = { version = "1.18", features = ["rt", "rt-multi-thread", "macros"] }
